### ISSUE TITLE
Asks for username/password nonstop

### ISSUE THREAD

**Issue by Wickemu** [klattimer/KodiPlay#1]
I tried sending something from YouTube and got a prompt to enter the username/password for my xbmc login (which was confusing in itself since I'd already put that in the extension preferences).  Then it asked for it again. and again. the video never cast; it just kept asking for my password until I hit cancel.

I verified that I'm using the correct login information, so that can't be the problem.

**Comment by Wickemu** [comment]
Oddly, the problem went away when I switched from the local address to the remote address.

**Comment by klattimer** [comment]
I believe this is a bug in the kodi youtube plugin, I had to mess around with kodi to get the password prompt to go away properly.
