### ISSUE TITLE
Missing `/bin/true` on El Capitan

### ISSUE THREAD

**Issue by fiedl** [klattimer/KodiPlay#3]
Hi, nice idea for an extension!

Unfortunately, it doesn't work for me on El Capitan.

I've tried your direct link (http://www.qdh.org.uk/KodiPlay.safariextz). But the extension does not show up in the list in safari.

When trying to compile, I get the error 
**error: can't exec '/bin/true' (No such file or directory)**.

Indeed, `/bin/true` is missing. Symlinking is not permitted, even with `sudo`:

```
➜  sudo ln -s /usr/bin/true /bin/true
ln: /bin/true: Operation not permitted
```

Any clues? Cheers!

---

OS X El Capitan 10.11.1 (15B42)
Xcode Version 7.1 (7B91b)

**Comment by klattimer** [comment]
No idea, working fine for me. I can give it a look later on this evening.

**Comment by fiedl** [comment]
I've tried to change `buildToolPath = /bin/true` to `buildToolPath = /usr/bin/true` in  [project.pbxproj#L69](https://github.com/klattimer/KodiPlay/blob/master/KodiPlay.xcodeproj/project.pbxproj#L69).

Then, the build succeeds. But, no `.safariextz` file is produced.

How would I install the extension after the build has succeeded? Thanks!

**Comment by klattimer** [comment]
Ah now I understand your problem... You don't build this with XCode you build it with Safari (developer tools enabled)

**Comment by fiedl** [comment]
If I open "Extension Builder" in Safari, click "add extension" and try to select KodiPlay, all files are greyed out, i.e. I can't add KodiPlay in the Extension Builder.

<img width="703" alt="bildschirmfoto 2015-11-06 um 14 48 31" src="https://cloud.githubusercontent.com/assets/1679688/10998450/79dcbc82-8495-11e5-97d6-06aebcffa2b3.png">

**Comment by klattimer** [comment]
I think rather than asking me, you should spend some time learning how safari extension building works. Or just install from the package which _should_ show up when opened with safari.

**Comment by fiedl** [comment]
Well, I would gladly use the package, but it does not show up in the extensions list after installing it.

> I've tried your direct link (http://www.qdh.org.uk/KodiPlay.safariextz). But the extension does not show up in the list in safari.

But, maybe you can give me a literature pointer on how to build the extension?

Also, I've noticed that if I create a new extension in Safari, a `.safariextension` file is created. But no such file is in your repo. Do we just have a Safari version mismatch here?

I'm using _Safari Version 9.0.1 (11601.2.7.2)_ on OS X 10.11.1 (15B42).

**Comment by fiedl** [comment]
The solution was simple:

I've checked out your project with `git clone git@github.com:klattimer/KodiPlay.git`. This has created the folder `KodiPlay`. In order to use this with the "Extension Builder", I had to **rename the project folder to `KodiPlay.safariextension`**.

Thanks anyway.
